### ISSUE TITLE
Terceira Avaliação por Pares

### ISSUE THREAD

**Issue by mileneserrano** [UnBParadigmas2020-2/2020.2_G2_SMA_PathPlanner#1]
Olá Pessoal!

O Grupo 02 irá avaliar o Grupo 04 nessa terceira avaliação por pares.
Os templates, em doc ou pdf, e demais informações para essa avaliação constam disponíveis no Moodle.
Basta entrar no Módulo Paradigma SMA no Moodle, e procurar por "Terceira Avaliação por Pares - Módulo SMA".

Atenciosamente.

**Comment by dansousamelo** [comment]
Feito!
